# Generated by Django 3.0.7 on 2020-08-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_replycomment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
